title: Renoir Boulanger - blogtini
user: renoirb
repo: blogtini
git_provider: github
img_site: https://files.mastodon.social/accounts/avatars/000/570/310/original/4f15ee9e18059aba.jpeg
posts_per_page: 10
remove_blur: true

